<a href="https://colab.research.google.com/github/Babatunde-source/Data-science-batch-A/blob/main/Assgt3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creat 1D array
import numpy as np
my_array_1d= np.array([1, 2, 3, 4, 5, 6, 7])
print (my_array_1d)



[1 2 3 4 5 6 7]


In [ ]:
#1D array:we need only one index to access element ata any position
#call the value at index 5
print('element at index 5:' , my_array_1d[5])

#ndarray are mutable(changeable), here we can change an element at index 5
my_array_1d[5]= 15
print('element at index 5 after change:', my_array_1d[5])



element at index 5: 6
element at index 5 after change: 15


In [ ]:
print (my_array_1d)



[ 1  2  3  4  5 15  7]


In [ ]:
#get the values in the range
print('elements in the range:', my_array_1d[2:5]) #a:b - including a, until (and excluding) b

#we can change values in the range as well
my_array_1d[2:5] = 20
print('elements in the range after change:', my_array_1d[2:5])



elements in the range: [3 4 5]
elements in the range after change: [20 20 20]


In [8]:
#2D arrays(two indexing): first one for the row and second one for the column

#creat 2D array
my_2d_array= np.array([[1,2 ,3 ,4 ,5 ],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25]])
print('my original array:', my_2d_array,'\n')

#slicing: generates an array of the same rank
my_array_copy= my_2d_array.copy()
row_slice= my_array_copy[1:3, :] #a:b - including a, until (and excluding) b
print('sliced array on [1:3,:]: \n', row_slice)



my original array: [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]] 

sliced array on [1:3,:]: 
 [[11 12 13 14 15]
 [21 22 23 24 25]]


In [9]:
#if we change the sliced array it will change the original array too
row_slice[1:4, :]= 12

print('sliced array:\n', row_slice, '\n')
print('original array:\n', my_2d_array)



sliced array:
 [[11 12 13 14 15]
 [12 12 12 12 12]] 

original array:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [12]:
#we can do the slicing for column as well
slice_col= my_2d_array[:, 1:5]
print (slice_col)

[[ 2  3  4  5]
 [12 13 14 15]
 [22 23 24 25]]


In [13]:
#filters to select just those elements which meets certain criteria
#select the elements that are greater than 10
slice_col[slice_col> 10]




array([12, 13, 14, 15, 22, 23, 24, 25])

In [14]:
#addition can be done in two ways:with the plus sign, wih the 'add' numpy function
arr_a =np.array([[10, 20, 30],[40, 50, 60]])
arr_b =np.array([[11, 21, 31],[41, 51, 61]])

print("Array A")
print(arr_a, '\n')

print("Array B")
print(arr_a, '\n')

print("Direct Addition")
print(arr_a + arr_b, '\n')

print("Numpy A ddition")
print(np.add(arr_a , arr_b))



Array A
[[10 20 30]
 [40 50 60]] 

Array B
[[10 20 30]
 [40 50 60]] 

Direct Addition
[[ 21  41  61]
 [ 81 101 121]] 

Numpy A ddition
[[ 21  41  61]
 [ 81 101 121]]


In [16]:
#the same is with the subtraction
print("Direct subtraction")
print(arr_b - arr_a, '\n')

print("Numpy subtraction")
print(np.subtract(arr_b,arr_a))





Direct subtraction
[[1 1 1]
 [1 1 1]] 

Numpy subtraction
[[1 1 1]
 [1 1 1]]


In [17]:
#multiplication
print("Direct multiplication")
print(arr_a *arr_b,'\n')

print("Numpy multiplication")
print(np.multiply(arr_a,arr_b))



Direct multiplication
[[ 110  420  930]
 [1640 2550 3660]] 

Numpy multiplication
[[ 110  420  930]
 [1640 2550 3660]]


In [18]:
#division
print("Direct division")
print(arr_b / arr_a, '\n')

print("Numpy division")
print(np.divide(arr_b, arr_a))



Direct division
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]] 

Numpy division
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]]


In [19]:
#square root
print (np.sqrt(arr_a))



[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [20]:
#exponent(e**x)
print (np.exp(arr_a))



[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [21]:
#power
print(np.power(arr_a,2))



[[ 100  400  900]
 [1600 2500 3600]]


In [22]:
#Assignment
arr_x= np.array([[70, 80, 90],[71, 81, 91]])
arr_y= np.array([[22, 33, 44],[23, 34, 45]])

print("Array X")
print(arr_x,'\n')

print("Array Y")
print(arr_y, '\n')

print("Direct addition")
print(arr_x + arr_y, '\n')

print("Direct subtraction")
print(arr_y - arr_x, '\n')

print("Direct multiplication")
print(arr_x * 5, '\n')

print("Direct division")
print(arr_y / 10, '\n')





Array X
[[70 80 90]
 [71 81 91]] 

Array Y
[[22 33 44]
 [23 34 45]] 

Direct addition
[[ 92 113 134]
 [ 94 115 136]] 

Direct subtraction
[[-48 -47 -46]
 [-48 -47 -46]] 

Direct multiplication
[[350 400 450]
 [355 405 455]] 

Direct division
[[2.2 3.3 4.4]
 [2.3 3.4 4.5]] 



In [25]:
import pandas as pd

In [26]:
#creating panda series from list
lts= ['a', 'b', 'c', 'd', 'e']
ser_1 = pd.Series(lts)

print (ser_1)



0    a
1    b
2    c
3    d
4    e
dtype: object


In [29]:
#creating panda series from array
arr= np.array([10, 20, 30, 40, 50])
ser_2= pd.Series(arr)

print(ser_2)



0    10
1    20
2    30
3    40
4    50
dtype: int64


In [30]:
#create series with specific indexing
ser_3= pd.Series(arr, index=['a', 'b', 'c', 'd','e'])

print(ser_3)



a    10
b    20
c    30
d    40
e    50
dtype: int64


In [31]:
#accessing an element using the index
print(ser_3[3], '\n\n')
print(ser_3[[0, 2, 4]], '\n\n')
print(ser_3[:3])



40 


a    10
c    30
e    50
dtype: int64 


a    10
b    20
c    30
dtype: int64


In [32]:
#accessing element using index label
print(ser_3['a'])
print(ser_3[['b', 'a']])




10
b    20
a    10
dtype: int64


In [35]:
#creating from a list of lists
pet_info = [['Howard', 10, 'Goat'],['Lucy', 4, 'Fish'],['Roco', 8, 'Lizard']]
pet_info



[['Howard', 10, 'Goat'], ['Lucy', 4, 'Fish'], ['Roco', 8, 'Lizard']]

In [36]:
pet_df = pd.DataFrame(pet_info, columns= ['Name','Age', 'Type'], index=['A', 'B', 'C'])
pet_df



Name  Age    Type
A  Howard   10    Goat
B    Lucy    4    Fish
C    Roco    8  Lizard

In [37]:
pet_df['Name']



A    Howard
B      Lucy
C      Roco
Name: Name, dtype: object

In [38]:
pet_df[['Name', 'Age']]



Name  Age
A  Howard   10
B    Lucy    4
C    Roco    8

In [39]:
#Exercise2
pet_df['Type']



A      Goat
B      Fish
C    Lizard
Name: Type, dtype: object

In [40]:
pet_df.iloc[1]



Name    Lucy
Age        4
Type    Fish
Name: B, dtype: object

In [41]:
pet_df.loc['B']



Name    Lucy
Age        4
Type    Fish
Name: B, dtype: object

In [42]:
#creating a list of list
pet_info= [[68.478, 190.686 ], [71.28444, 199.6353], [64.98046, 166.8215], [66.76188, 178.7975 ],[68.76616, 185.7722 ],[68.99254, 193.755]]
pet_info



[[68.478, 190.686],
 [71.28444, 199.6353],
 [64.98046, 166.8215],
 [66.76188, 178.7975],
 [68.76616, 185.7722],
 [68.99254, 193.755]]

In [44]:
pet_df= pd.DataFrame(pet_info, columns= ['Weight', 'Height'], index=['A','B','C','D','E','F'])
pet_df



Weight    Height
A  68.47800  190.6860
B  71.28444  199.6353
C  64.98046  166.8215
D  66.76188  178.7975
E  68.76616  185.7722
F  68.99254  193.7550

In [45]:
pet_df.iloc[4]



Weight     68.76616
Height    185.77220
Name: E, dtype: float64

In [48]:
pet_df['Height']

A    190.6860
B    199.6353
C    166.8215
D    178.7975
E    185.7722
F    193.7550
Name: Height, dtype: float64