##**NumPy**

Documentation - https://numpy.org/doc/

In [ ]:
# A simple function to evaluate simple interest formula
def simple_interest(P, R, T):
    simpleInterest = (P * R * T)/100 
    return simpleInterest

In [ ]:
simple_interest(1800, 0.05, 2)

1.8

In [ ]:
def odd_number(n = 200):
   # formula for even number = n + 2
   # formula for odd number = n + 1
   for i in (1, n):
       x1 = 2*i + 1 # Odd number
       x2 = 2 * i   # even number
       return x1

### Import Numpy and Pandas Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
print("NumPy version: " + np.version.version)

NumPy version: 1.19.5


In [4]:
print("Pandas version: " + pd.__version__)

#pip install pandas = 1.1.12

Pandas version: 1.1.5


### Creating Arrays

In [5]:
#create 1D numpy array from a list
sample = np.array([1, 2, 3, 4, 5])

print(sample)

[1 2 3 4 5]


In [6]:
type(sample)

numpy.ndarray

In [7]:
#1D numpy array from a list variable
list1 = [11, 22, 33, 44, 55]
arrayl1 = np.array(list1)

print(arrayl1)

[11 22 33 44 55]


In [8]:
print ("Array type = " + str(type(arrayl1)))
print ("Data type = " + str(arrayl1.dtype))

Array type = <class 'numpy.ndarray'>
Data type = int64


In [9]:
#five element, one dimension
print(arrayl1.shape)

(5,)


In [10]:
type(arrayl1)

numpy.ndarray

In [11]:
# working with Range function.
my_range = range(2, 12)
list(my_range)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Notice how the second number is exclusive. 

In [12]:
range_with_i = range(1, 10, 2)

In [ ]:
list(range_with_i)

[1, 3, 5, 7, 9]

### Excercise 1

1.  Create a Python List using the range function.
1.  Convert the list into a NumPy array
1.  Check the data type to make sure it is a NumPy array
1.  Convert that array back into a list



In [20]:
my_range= range(4, 15)
list(my_range)



[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [21]:
list1= [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
arrayl1= np.array(list1)

print(arrayl1)



[ 4  5  6  7  8  9 10 11 12 13 14]


In [22]:
type(arrayl1)




numpy.ndarray

In [24]:
arrayl1= [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
list1

print (list1)

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


### Python Matrices (2D) to NumPy Array

In [ ]:
 mymatrix = [[4,2,9],[32,43,68],[73,8,9]]
 mymatrix

[[4, 2, 9], [32, 43, 68], [73, 8, 9]]

In [ ]:
#Create a matrix (2D array)
numpy_array = np.array(mymatrix)

In [ ]:
numpy_array

array([[ 4,  2,  9],
       [32, 43, 68],
       [73,  8,  9]])

In [ ]:
type(numpy_array)

numpy.ndarray

In [ ]:
# Convert a NumPy Array into a Pandas DataFrame
df_from_array = pd.DataFrame(numpy_array)
df_from_array

0   1   2
0   4   2   9
1  32  43  68
2  73   8   9

### Assignment - 2 

1. Create a matrix from a list.
2. Convert the matrix into a NumPy array
3. Check the data type to make sure it is a NumPy array
4. Convert the NumPy array to a Pandas DataFrame

In [27]:
mymatrix= [[5, 10, 15],[11, 30, 41],[22, 7, 19]]
mymatrix

[[5, 10, 15], [11, 30, 41], [22, 7, 19]]

In [29]:
numpy_array= np.array(mymatrix)



In [31]:
numpy_array



array([[ 5, 10, 15],
       [11, 30, 41],
       [22,  7, 19]])

In [32]:
type(numpy_array)



numpy.ndarray

In [33]:
#convert the NumPy array into a Pandas Dataframe
df_from_array= pd.DataFrame(numpy_array)
df_from_array



0   1   2
0   5  10  15
1  11  30  41
2  22   7  19